//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qntCygnusWF.Cygnus {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalFunctionalClass", Namespace="WSPersonasCygnus")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(qntCygnusWF.Cygnus.Resultado))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(qntCygnusWF.Cygnus.RespuestaPermite))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(qntCygnusWF.Cygnus.General))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(qntCygnusWF.Cygnus.RespuestaCrea))]
    public partial class SalFunctionalClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Resultado", Namespace="WSPersonasCygnus")]
    [System.SerializableAttribute()]
    public partial class Resultado : qntCygnusWF.Cygnus.SalFunctionalClass {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultadoMemberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="Resultado", EmitDefaultValue=false)]
        public string ResultadoMember {
            get {
                return this.ResultadoMemberField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultadoMemberField, value) != true)) {
                    this.ResultadoMemberField = value;
                    this.RaisePropertyChanged("ResultadoMember");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaPermite", Namespace="WSPersonasCygnus")]
    [System.SerializableAttribute()]
    public partial class RespuestaPermite : qntCygnusWF.Cygnus.SalFunctionalClass {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string R_s_respuestaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string R_s_respuesta {
            get {
                return this.R_s_respuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.R_s_respuestaField, value) != true)) {
                    this.R_s_respuestaField = value;
                    this.RaisePropertyChanged("R_s_respuesta");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="General", Namespace="WSPersonasCygnus")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(qntCygnusWF.Cygnus.RespuestaCrea))]
    public partial class General : qntCygnusWF.Cygnus.SalFunctionalClass {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaCrea", Namespace="WSPersonasCygnus")]
    [System.SerializableAttribute()]
    public partial class RespuestaCrea : qntCygnusWF.Cygnus.General {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoCygnusField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultadoField, value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MensajeError {
            get {
                return this.MensajeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeErrorField, value) != true)) {
                    this.MensajeErrorField = value;
                    this.RaisePropertyChanged("MensajeError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CodigoCygnus {
            get {
                return this.CodigoCygnusField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoCygnusField, value) != true)) {
                    this.CodigoCygnusField = value;
                    this.RaisePropertyChanged("CodigoCygnus");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="WSPersonasCygnus", ConfigurationName="Cygnus.WSPersonasCygnusSoap")]
    public interface WSPersonasCygnusSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento p_dfn_nat_codigo del espacio de nombres WSPersonasCygnus no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="WSPersonasCygnus/WC_CREAR_PERSONABASICO", ReplyAction="*")]
        qntCygnusWF.Cygnus.WC_CREAR_PERSONABASICOResponse WC_CREAR_PERSONABASICO(qntCygnusWF.Cygnus.WC_CREAR_PERSONABASICORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="WSPersonasCygnus/WC_CREAR_PERSONABASICO", ReplyAction="*")]
        System.Threading.Tasks.Task<qntCygnusWF.Cygnus.WC_CREAR_PERSONABASICOResponse> WC_CREAR_PERSONABASICOAsync(qntCygnusWF.Cygnus.WC_CREAR_PERSONABASICORequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento pws_codigoPer del espacio de nombres WSPersonasCygnus no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="WSPersonasCygnus/WC_CREAR_ROLPERSONAS", ReplyAction="*")]
        qntCygnusWF.Cygnus.WC_CREAR_ROLPERSONASResponse WC_CREAR_ROLPERSONAS(qntCygnusWF.Cygnus.WC_CREAR_ROLPERSONASRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="WSPersonasCygnus/WC_CREAR_ROLPERSONAS", ReplyAction="*")]
        System.Threading.Tasks.Task<qntCygnusWF.Cygnus.WC_CREAR_ROLPERSONASResponse> WC_CREAR_ROLPERSONASAsync(qntCygnusWF.Cygnus.WC_CREAR_ROLPERSONASRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento p_dfn_nat_codigo del espacio de nombres WSPersonasCygnus no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="WSPersonasCygnus/WC_CREAR_PERSONAS", ReplyAction="*")]
        qntCygnusWF.Cygnus.WC_CREAR_PERSONASResponse WC_CREAR_PERSONAS(qntCygnusWF.Cygnus.WC_CREAR_PERSONASRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="WSPersonasCygnus/WC_CREAR_PERSONAS", ReplyAction="*")]
        System.Threading.Tasks.Task<qntCygnusWF.Cygnus.WC_CREAR_PERSONASResponse> WC_CREAR_PERSONASAsync(qntCygnusWF.Cygnus.WC_CREAR_PERSONASRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ps_identificacion del espacio de nombres WSPersonasCygnus no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="WSPersonasCygnus/WC_ALMACENAR_ACT_SOLICITANTE", ReplyAction="*")]
        qntCygnusWF.Cygnus.WC_ALMACENAR_ACT_SOLICITANTEResponse WC_ALMACENAR_ACT_SOLICITANTE(qntCygnusWF.Cygnus.WC_ALMACENAR_ACT_SOLICITANTERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="WSPersonasCygnus/WC_ALMACENAR_ACT_SOLICITANTE", ReplyAction="*")]
        System.Threading.Tasks.Task<qntCygnusWF.Cygnus.WC_ALMACENAR_ACT_SOLICITANTEResponse> WC_ALMACENAR_ACT_SOLICITANTEAsync(qntCygnusWF.Cygnus.WC_ALMACENAR_ACT_SOLICITANTERequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento pws_bd del espacio de nombres WSPersonasCygnus no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="WSPersonasCygnus/pruebaConexion", ReplyAction="*")]
        qntCygnusWF.Cygnus.pruebaConexionResponse pruebaConexion(qntCygnusWF.Cygnus.pruebaConexionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="WSPersonasCygnus/pruebaConexion", ReplyAction="*")]
        System.Threading.Tasks.Task<qntCygnusWF.Cygnus.pruebaConexionResponse> pruebaConexionAsync(qntCygnusWF.Cygnus.pruebaConexionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WC_CREAR_PERSONABASICORequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WC_CREAR_PERSONABASICO", Namespace="WSPersonasCygnus", Order=0)]
        public qntCygnusWF.Cygnus.WC_CREAR_PERSONABASICORequestBody Body;
        
        public WC_CREAR_PERSONABASICORequest() {
        }
        
        public WC_CREAR_PERSONABASICORequest(qntCygnusWF.Cygnus.WC_CREAR_PERSONABASICORequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WSPersonasCygnus")]
    public partial class WC_CREAR_PERSONABASICORequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string p_dfn_nat_codigo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pws_identific;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string p_w_n_tipoiden;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string p_w_d_fecexp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string p_dfs_nat_nombres;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string p_dfs_nat_apellidos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string p_w_s_tipodepersona;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string p_w_s_direccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string p_w_n_ciudad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string p_w_s_telefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string p_w_s_direcelec;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string pws_bd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string pws_usu;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string pws_psw;
        
        public WC_CREAR_PERSONABASICORequestBody() {
        }
        
        public WC_CREAR_PERSONABASICORequestBody(string p_dfn_nat_codigo, string pws_identific, string p_w_n_tipoiden, string p_w_d_fecexp, string p_dfs_nat_nombres, string p_dfs_nat_apellidos, string p_w_s_tipodepersona, string p_w_s_direccion, string p_w_n_ciudad, string p_w_s_telefono, string p_w_s_direcelec, string pws_bd, string pws_usu, string pws_psw) {
            this.p_dfn_nat_codigo = p_dfn_nat_codigo;
            this.pws_identific = pws_identific;
            this.p_w_n_tipoiden = p_w_n_tipoiden;
            this.p_w_d_fecexp = p_w_d_fecexp;
            this.p_dfs_nat_nombres = p_dfs_nat_nombres;
            this.p_dfs_nat_apellidos = p_dfs_nat_apellidos;
            this.p_w_s_tipodepersona = p_w_s_tipodepersona;
            this.p_w_s_direccion = p_w_s_direccion;
            this.p_w_n_ciudad = p_w_n_ciudad;
            this.p_w_s_telefono = p_w_s_telefono;
            this.p_w_s_direcelec = p_w_s_direcelec;
            this.pws_bd = pws_bd;
            this.pws_usu = pws_usu;
            this.pws_psw = pws_psw;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WC_CREAR_PERSONABASICOResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WC_CREAR_PERSONABASICOResponse", Namespace="WSPersonasCygnus", Order=0)]
        public qntCygnusWF.Cygnus.WC_CREAR_PERSONABASICOResponseBody Body;
        
        public WC_CREAR_PERSONABASICOResponse() {
        }
        
        public WC_CREAR_PERSONABASICOResponse(qntCygnusWF.Cygnus.WC_CREAR_PERSONABASICOResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WSPersonasCygnus")]
    public partial class WC_CREAR_PERSONABASICOResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string WC_CREAR_PERSONABASICOResult;
        
        public WC_CREAR_PERSONABASICOResponseBody() {
        }
        
        public WC_CREAR_PERSONABASICOResponseBody(string WC_CREAR_PERSONABASICOResult) {
            this.WC_CREAR_PERSONABASICOResult = WC_CREAR_PERSONABASICOResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WC_CREAR_ROLPERSONASRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WC_CREAR_ROLPERSONAS", Namespace="WSPersonasCygnus", Order=0)]
        public qntCygnusWF.Cygnus.WC_CREAR_ROLPERSONASRequestBody Body;
        
        public WC_CREAR_ROLPERSONASRequest() {
        }
        
        public WC_CREAR_ROLPERSONASRequest(qntCygnusWF.Cygnus.WC_CREAR_ROLPERSONASRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WSPersonasCygnus")]
    public partial class WC_CREAR_ROLPERSONASRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pws_codigoPer;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pws_numRol;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pws_fechaInicio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pws_bd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string pws_usu;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string pws_psw;
        
        public WC_CREAR_ROLPERSONASRequestBody() {
        }
        
        public WC_CREAR_ROLPERSONASRequestBody(string pws_codigoPer, string pws_numRol, string pws_fechaInicio, string pws_bd, string pws_usu, string pws_psw) {
            this.pws_codigoPer = pws_codigoPer;
            this.pws_numRol = pws_numRol;
            this.pws_fechaInicio = pws_fechaInicio;
            this.pws_bd = pws_bd;
            this.pws_usu = pws_usu;
            this.pws_psw = pws_psw;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WC_CREAR_ROLPERSONASResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WC_CREAR_ROLPERSONASResponse", Namespace="WSPersonasCygnus", Order=0)]
        public qntCygnusWF.Cygnus.WC_CREAR_ROLPERSONASResponseBody Body;
        
        public WC_CREAR_ROLPERSONASResponse() {
        }
        
        public WC_CREAR_ROLPERSONASResponse(qntCygnusWF.Cygnus.WC_CREAR_ROLPERSONASResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WSPersonasCygnus")]
    public partial class WC_CREAR_ROLPERSONASResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public qntCygnusWF.Cygnus.RespuestaCrea WC_CREAR_ROLPERSONASResult;
        
        public WC_CREAR_ROLPERSONASResponseBody() {
        }
        
        public WC_CREAR_ROLPERSONASResponseBody(qntCygnusWF.Cygnus.RespuestaCrea WC_CREAR_ROLPERSONASResult) {
            this.WC_CREAR_ROLPERSONASResult = WC_CREAR_ROLPERSONASResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WC_CREAR_PERSONASRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WC_CREAR_PERSONAS", Namespace="WSPersonasCygnus", Order=0)]
        public qntCygnusWF.Cygnus.WC_CREAR_PERSONASRequestBody Body;
        
        public WC_CREAR_PERSONASRequest() {
        }
        
        public WC_CREAR_PERSONASRequest(qntCygnusWF.Cygnus.WC_CREAR_PERSONASRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WSPersonasCygnus")]
    public partial class WC_CREAR_PERSONASRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string p_dfn_nat_codigo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string p_w_s_tipodepersona;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string p_dfs_nat_codaso;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pws_identific;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string p_dfn_nat_tipcli;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string p_w_n_tipoiden;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string p_dfn_nat_lugexp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string p_w_d_fecexp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string p_dfs_nat_nombres;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string p_dfs_nat_apellidos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string p_dfn_nat_ciunac;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string p_w_d_fecnac;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string p_cbs_nat_res_aux;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string p_w_d_fecres;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string p_w_s_sexo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string p_s_tesoro;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string p_dfs_nat_estciv;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string p_dfn_nat_percar;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string p_dfs_nat_cla;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string p_dfs_nat_claint;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string p_dfs_nat_nroact;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string p_df_nat_rut;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string p_df_cod_of;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string p_dfn_nacionalidad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string p_dfn_nacionalidad2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string p_dfn_NroHijos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string p_dfs_nat_apellido1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string p_dfs_nat_apellido2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string p_cmb_Estrato;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=29)]
        public string p_cb_nat_mujer_fam;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=30)]
        public string p_cb_operacion_ext;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=31)]
        public string p_estado_act;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=32)]
        public string p_w_s_direccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=33)]
        public string p_w_n_ciudad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=34)]
        public string p_w_s_telefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=35)]
        public string p_w_s_direcelec;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=36)]
        public string ps_i_vinculac_lab;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=37)]
        public string ps_c_asesor_com;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=38)]
        public string ps_n_salario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=39)]
        public string ps_i_nivel_estudio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=40)]
        public string ps_i_profesion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=41)]
        public string ps_i_cargo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=42)]
        public string ps_i_tipo_cont;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=43)]
        public string ps_n_modeloScoring;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=44)]
        public string pws_bd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=45)]
        public string pws_usu;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=46)]
        public string pws_psw;
        
        public WC_CREAR_PERSONASRequestBody() {
        }
        
        public WC_CREAR_PERSONASRequestBody(
                    string p_dfn_nat_codigo, 
                    string p_w_s_tipodepersona, 
                    string p_dfs_nat_codaso, 
                    string pws_identific, 
                    string p_dfn_nat_tipcli, 
                    string p_w_n_tipoiden, 
                    string p_dfn_nat_lugexp, 
                    string p_w_d_fecexp, 
                    string p_dfs_nat_nombres, 
                    string p_dfs_nat_apellidos, 
                    string p_dfn_nat_ciunac, 
                    string p_w_d_fecnac, 
                    string p_cbs_nat_res_aux, 
                    string p_w_d_fecres, 
                    string p_w_s_sexo, 
                    string p_s_tesoro, 
                    string p_dfs_nat_estciv, 
                    string p_dfn_nat_percar, 
                    string p_dfs_nat_cla, 
                    string p_dfs_nat_claint, 
                    string p_dfs_nat_nroact, 
                    string p_df_nat_rut, 
                    string p_df_cod_of, 
                    string p_dfn_nacionalidad, 
                    string p_dfn_nacionalidad2, 
                    string p_dfn_NroHijos, 
                    string p_dfs_nat_apellido1, 
                    string p_dfs_nat_apellido2, 
                    string p_cmb_Estrato, 
                    string p_cb_nat_mujer_fam, 
                    string p_cb_operacion_ext, 
                    string p_estado_act, 
                    string p_w_s_direccion, 
                    string p_w_n_ciudad, 
                    string p_w_s_telefono, 
                    string p_w_s_direcelec, 
                    string ps_i_vinculac_lab, 
                    string ps_c_asesor_com, 
                    string ps_n_salario, 
                    string ps_i_nivel_estudio, 
                    string ps_i_profesion, 
                    string ps_i_cargo, 
                    string ps_i_tipo_cont, 
                    string ps_n_modeloScoring, 
                    string pws_bd, 
                    string pws_usu, 
                    string pws_psw) {
            this.p_dfn_nat_codigo = p_dfn_nat_codigo;
            this.p_w_s_tipodepersona = p_w_s_tipodepersona;
            this.p_dfs_nat_codaso = p_dfs_nat_codaso;
            this.pws_identific = pws_identific;
            this.p_dfn_nat_tipcli = p_dfn_nat_tipcli;
            this.p_w_n_tipoiden = p_w_n_tipoiden;
            this.p_dfn_nat_lugexp = p_dfn_nat_lugexp;
            this.p_w_d_fecexp = p_w_d_fecexp;
            this.p_dfs_nat_nombres = p_dfs_nat_nombres;
            this.p_dfs_nat_apellidos = p_dfs_nat_apellidos;
            this.p_dfn_nat_ciunac = p_dfn_nat_ciunac;
            this.p_w_d_fecnac = p_w_d_fecnac;
            this.p_cbs_nat_res_aux = p_cbs_nat_res_aux;
            this.p_w_d_fecres = p_w_d_fecres;
            this.p_w_s_sexo = p_w_s_sexo;
            this.p_s_tesoro = p_s_tesoro;
            this.p_dfs_nat_estciv = p_dfs_nat_estciv;
            this.p_dfn_nat_percar = p_dfn_nat_percar;
            this.p_dfs_nat_cla = p_dfs_nat_cla;
            this.p_dfs_nat_claint = p_dfs_nat_claint;
            this.p_dfs_nat_nroact = p_dfs_nat_nroact;
            this.p_df_nat_rut = p_df_nat_rut;
            this.p_df_cod_of = p_df_cod_of;
            this.p_dfn_nacionalidad = p_dfn_nacionalidad;
            this.p_dfn_nacionalidad2 = p_dfn_nacionalidad2;
            this.p_dfn_NroHijos = p_dfn_NroHijos;
            this.p_dfs_nat_apellido1 = p_dfs_nat_apellido1;
            this.p_dfs_nat_apellido2 = p_dfs_nat_apellido2;
            this.p_cmb_Estrato = p_cmb_Estrato;
            this.p_cb_nat_mujer_fam = p_cb_nat_mujer_fam;
            this.p_cb_operacion_ext = p_cb_operacion_ext;
            this.p_estado_act = p_estado_act;
            this.p_w_s_direccion = p_w_s_direccion;
            this.p_w_n_ciudad = p_w_n_ciudad;
            this.p_w_s_telefono = p_w_s_telefono;
            this.p_w_s_direcelec = p_w_s_direcelec;
            this.ps_i_vinculac_lab = ps_i_vinculac_lab;
            this.ps_c_asesor_com = ps_c_asesor_com;
            this.ps_n_salario = ps_n_salario;
            this.ps_i_nivel_estudio = ps_i_nivel_estudio;
            this.ps_i_profesion = ps_i_profesion;
            this.ps_i_cargo = ps_i_cargo;
            this.ps_i_tipo_cont = ps_i_tipo_cont;
            this.ps_n_modeloScoring = ps_n_modeloScoring;
            this.pws_bd = pws_bd;
            this.pws_usu = pws_usu;
            this.pws_psw = pws_psw;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WC_CREAR_PERSONASResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WC_CREAR_PERSONASResponse", Namespace="WSPersonasCygnus", Order=0)]
        public qntCygnusWF.Cygnus.WC_CREAR_PERSONASResponseBody Body;
        
        public WC_CREAR_PERSONASResponse() {
        }
        
        public WC_CREAR_PERSONASResponse(qntCygnusWF.Cygnus.WC_CREAR_PERSONASResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WSPersonasCygnus")]
    public partial class WC_CREAR_PERSONASResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string WC_CREAR_PERSONASResult;
        
        public WC_CREAR_PERSONASResponseBody() {
        }
        
        public WC_CREAR_PERSONASResponseBody(string WC_CREAR_PERSONASResult) {
            this.WC_CREAR_PERSONASResult = WC_CREAR_PERSONASResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WC_ALMACENAR_ACT_SOLICITANTERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WC_ALMACENAR_ACT_SOLICITANTE", Namespace="WSPersonasCygnus", Order=0)]
        public qntCygnusWF.Cygnus.WC_ALMACENAR_ACT_SOLICITANTERequestBody Body;
        
        public WC_ALMACENAR_ACT_SOLICITANTERequest() {
        }
        
        public WC_ALMACENAR_ACT_SOLICITANTERequest(qntCygnusWF.Cygnus.WC_ALMACENAR_ACT_SOLICITANTERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WSPersonasCygnus")]
    public partial class WC_ALMACENAR_ACT_SOLICITANTERequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ps_identificacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string s_actividad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string s_empresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string s_fec_ingreso;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string s_contrato;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string s_cargo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string s_dir_empresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string s_ciudad_empresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string s_ingreso_principal;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string s_gastos_obligaciones;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string s_otros_ingresos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string s_total_activos;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string s_total_ingresomes;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string s_total_pasivo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string s_renta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string s_declarante_renta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string s_vivienda;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string s_prendas_vivienda;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string s_vehiculo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string s_prendas_vehiculo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string s_otros_bienes;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string s_otros_descripcion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string s_barrio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string ps_db;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string ps_usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string ps_clave;
        
        public WC_ALMACENAR_ACT_SOLICITANTERequestBody() {
        }
        
        public WC_ALMACENAR_ACT_SOLICITANTERequestBody(
                    string ps_identificacion, 
                    string s_actividad, 
                    string s_empresa, 
                    string s_fec_ingreso, 
                    string s_contrato, 
                    string s_cargo, 
                    string s_dir_empresa, 
                    string s_ciudad_empresa, 
                    string s_ingreso_principal, 
                    string s_gastos_obligaciones, 
                    string s_otros_ingresos, 
                    string s_total_activos, 
                    string s_total_ingresomes, 
                    string s_total_pasivo, 
                    string s_renta, 
                    string s_declarante_renta, 
                    string s_vivienda, 
                    string s_prendas_vivienda, 
                    string s_vehiculo, 
                    string s_prendas_vehiculo, 
                    string s_otros_bienes, 
                    string s_otros_descripcion, 
                    string s_barrio, 
                    string ps_db, 
                    string ps_usuario, 
                    string ps_clave) {
            this.ps_identificacion = ps_identificacion;
            this.s_actividad = s_actividad;
            this.s_empresa = s_empresa;
            this.s_fec_ingreso = s_fec_ingreso;
            this.s_contrato = s_contrato;
            this.s_cargo = s_cargo;
            this.s_dir_empresa = s_dir_empresa;
            this.s_ciudad_empresa = s_ciudad_empresa;
            this.s_ingreso_principal = s_ingreso_principal;
            this.s_gastos_obligaciones = s_gastos_obligaciones;
            this.s_otros_ingresos = s_otros_ingresos;
            this.s_total_activos = s_total_activos;
            this.s_total_ingresomes = s_total_ingresomes;
            this.s_total_pasivo = s_total_pasivo;
            this.s_renta = s_renta;
            this.s_declarante_renta = s_declarante_renta;
            this.s_vivienda = s_vivienda;
            this.s_prendas_vivienda = s_prendas_vivienda;
            this.s_vehiculo = s_vehiculo;
            this.s_prendas_vehiculo = s_prendas_vehiculo;
            this.s_otros_bienes = s_otros_bienes;
            this.s_otros_descripcion = s_otros_descripcion;
            this.s_barrio = s_barrio;
            this.ps_db = ps_db;
            this.ps_usuario = ps_usuario;
            this.ps_clave = ps_clave;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WC_ALMACENAR_ACT_SOLICITANTEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WC_ALMACENAR_ACT_SOLICITANTEResponse", Namespace="WSPersonasCygnus", Order=0)]
        public qntCygnusWF.Cygnus.WC_ALMACENAR_ACT_SOLICITANTEResponseBody Body;
        
        public WC_ALMACENAR_ACT_SOLICITANTEResponse() {
        }
        
        public WC_ALMACENAR_ACT_SOLICITANTEResponse(qntCygnusWF.Cygnus.WC_ALMACENAR_ACT_SOLICITANTEResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WSPersonasCygnus")]
    public partial class WC_ALMACENAR_ACT_SOLICITANTEResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public qntCygnusWF.Cygnus.Resultado WC_ALMACENAR_ACT_SOLICITANTEResult;
        
        public WC_ALMACENAR_ACT_SOLICITANTEResponseBody() {
        }
        
        public WC_ALMACENAR_ACT_SOLICITANTEResponseBody(qntCygnusWF.Cygnus.Resultado WC_ALMACENAR_ACT_SOLICITANTEResult) {
            this.WC_ALMACENAR_ACT_SOLICITANTEResult = WC_ALMACENAR_ACT_SOLICITANTEResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pruebaConexionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pruebaConexion", Namespace="WSPersonasCygnus", Order=0)]
        public qntCygnusWF.Cygnus.pruebaConexionRequestBody Body;
        
        public pruebaConexionRequest() {
        }
        
        public pruebaConexionRequest(qntCygnusWF.Cygnus.pruebaConexionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WSPersonasCygnus")]
    public partial class pruebaConexionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pws_bd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pws_usu;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pws_psw;
        
        public pruebaConexionRequestBody() {
        }
        
        public pruebaConexionRequestBody(string pws_bd, string pws_usu, string pws_psw) {
            this.pws_bd = pws_bd;
            this.pws_usu = pws_usu;
            this.pws_psw = pws_psw;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pruebaConexionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pruebaConexionResponse", Namespace="WSPersonasCygnus", Order=0)]
        public qntCygnusWF.Cygnus.pruebaConexionResponseBody Body;
        
        public pruebaConexionResponse() {
        }
        
        public pruebaConexionResponse(qntCygnusWF.Cygnus.pruebaConexionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="WSPersonasCygnus")]
    public partial class pruebaConexionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public qntCygnusWF.Cygnus.RespuestaPermite pruebaConexionResult;
        
        public pruebaConexionResponseBody() {
        }
        
        public pruebaConexionResponseBody(qntCygnusWF.Cygnus.RespuestaPermite pruebaConexionResult) {
            this.pruebaConexionResult = pruebaConexionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSPersonasCygnusSoapChannel : qntCygnusWF.Cygnus.WSPersonasCygnusSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSPersonasCygnusSoapClient : System.ServiceModel.ClientBase<qntCygnusWF.Cygnus.WSPersonasCygnusSoap>, qntCygnusWF.Cygnus.WSPersonasCygnusSoap {
        
        public WSPersonasCygnusSoapClient() {
        }
        
        public WSPersonasCygnusSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSPersonasCygnusSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSPersonasCygnusSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSPersonasCygnusSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        qntCygnusWF.Cygnus.WC_CREAR_PERSONABASICOResponse qntCygnusWF.Cygnus.WSPersonasCygnusSoap.WC_CREAR_PERSONABASICO(qntCygnusWF.Cygnus.WC_CREAR_PERSONABASICORequest request) {
            return base.Channel.WC_CREAR_PERSONABASICO(request);
        }
        
        public string WC_CREAR_PERSONABASICO(string p_dfn_nat_codigo, string pws_identific, string p_w_n_tipoiden, string p_w_d_fecexp, string p_dfs_nat_nombres, string p_dfs_nat_apellidos, string p_w_s_tipodepersona, string p_w_s_direccion, string p_w_n_ciudad, string p_w_s_telefono, string p_w_s_direcelec, string pws_bd, string pws_usu, string pws_psw) {
            qntCygnusWF.Cygnus.WC_CREAR_PERSONABASICORequest inValue = new qntCygnusWF.Cygnus.WC_CREAR_PERSONABASICORequest();
            inValue.Body = new qntCygnusWF.Cygnus.WC_CREAR_PERSONABASICORequestBody();
            inValue.Body.p_dfn_nat_codigo = p_dfn_nat_codigo;
            inValue.Body.pws_identific = pws_identific;
            inValue.Body.p_w_n_tipoiden = p_w_n_tipoiden;
            inValue.Body.p_w_d_fecexp = p_w_d_fecexp;
            inValue.Body.p_dfs_nat_nombres = p_dfs_nat_nombres;
            inValue.Body.p_dfs_nat_apellidos = p_dfs_nat_apellidos;
            inValue.Body.p_w_s_tipodepersona = p_w_s_tipodepersona;
            inValue.Body.p_w_s_direccion = p_w_s_direccion;
            inValue.Body.p_w_n_ciudad = p_w_n_ciudad;
            inValue.Body.p_w_s_telefono = p_w_s_telefono;
            inValue.Body.p_w_s_direcelec = p_w_s_direcelec;
            inValue.Body.pws_bd = pws_bd;
            inValue.Body.pws_usu = pws_usu;
            inValue.Body.pws_psw = pws_psw;
            qntCygnusWF.Cygnus.WC_CREAR_PERSONABASICOResponse retVal = ((qntCygnusWF.Cygnus.WSPersonasCygnusSoap)(this)).WC_CREAR_PERSONABASICO(inValue);
            return retVal.Body.WC_CREAR_PERSONABASICOResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<qntCygnusWF.Cygnus.WC_CREAR_PERSONABASICOResponse> qntCygnusWF.Cygnus.WSPersonasCygnusSoap.WC_CREAR_PERSONABASICOAsync(qntCygnusWF.Cygnus.WC_CREAR_PERSONABASICORequest request) {
            return base.Channel.WC_CREAR_PERSONABASICOAsync(request);
        }
        
        public System.Threading.Tasks.Task<qntCygnusWF.Cygnus.WC_CREAR_PERSONABASICOResponse> WC_CREAR_PERSONABASICOAsync(string p_dfn_nat_codigo, string pws_identific, string p_w_n_tipoiden, string p_w_d_fecexp, string p_dfs_nat_nombres, string p_dfs_nat_apellidos, string p_w_s_tipodepersona, string p_w_s_direccion, string p_w_n_ciudad, string p_w_s_telefono, string p_w_s_direcelec, string pws_bd, string pws_usu, string pws_psw) {
            qntCygnusWF.Cygnus.WC_CREAR_PERSONABASICORequest inValue = new qntCygnusWF.Cygnus.WC_CREAR_PERSONABASICORequest();
            inValue.Body = new qntCygnusWF.Cygnus.WC_CREAR_PERSONABASICORequestBody();
            inValue.Body.p_dfn_nat_codigo = p_dfn_nat_codigo;
            inValue.Body.pws_identific = pws_identific;
            inValue.Body.p_w_n_tipoiden = p_w_n_tipoiden;
            inValue.Body.p_w_d_fecexp = p_w_d_fecexp;
            inValue.Body.p_dfs_nat_nombres = p_dfs_nat_nombres;
            inValue.Body.p_dfs_nat_apellidos = p_dfs_nat_apellidos;
            inValue.Body.p_w_s_tipodepersona = p_w_s_tipodepersona;
            inValue.Body.p_w_s_direccion = p_w_s_direccion;
            inValue.Body.p_w_n_ciudad = p_w_n_ciudad;
            inValue.Body.p_w_s_telefono = p_w_s_telefono;
            inValue.Body.p_w_s_direcelec = p_w_s_direcelec;
            inValue.Body.pws_bd = pws_bd;
            inValue.Body.pws_usu = pws_usu;
            inValue.Body.pws_psw = pws_psw;
            return ((qntCygnusWF.Cygnus.WSPersonasCygnusSoap)(this)).WC_CREAR_PERSONABASICOAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        qntCygnusWF.Cygnus.WC_CREAR_ROLPERSONASResponse qntCygnusWF.Cygnus.WSPersonasCygnusSoap.WC_CREAR_ROLPERSONAS(qntCygnusWF.Cygnus.WC_CREAR_ROLPERSONASRequest request) {
            return base.Channel.WC_CREAR_ROLPERSONAS(request);
        }
        
        public qntCygnusWF.Cygnus.RespuestaCrea WC_CREAR_ROLPERSONAS(string pws_codigoPer, string pws_numRol, string pws_fechaInicio, string pws_bd, string pws_usu, string pws_psw) {
            qntCygnusWF.Cygnus.WC_CREAR_ROLPERSONASRequest inValue = new qntCygnusWF.Cygnus.WC_CREAR_ROLPERSONASRequest();
            inValue.Body = new qntCygnusWF.Cygnus.WC_CREAR_ROLPERSONASRequestBody();
            inValue.Body.pws_codigoPer = pws_codigoPer;
            inValue.Body.pws_numRol = pws_numRol;
            inValue.Body.pws_fechaInicio = pws_fechaInicio;
            inValue.Body.pws_bd = pws_bd;
            inValue.Body.pws_usu = pws_usu;
            inValue.Body.pws_psw = pws_psw;
            qntCygnusWF.Cygnus.WC_CREAR_ROLPERSONASResponse retVal = ((qntCygnusWF.Cygnus.WSPersonasCygnusSoap)(this)).WC_CREAR_ROLPERSONAS(inValue);
            return retVal.Body.WC_CREAR_ROLPERSONASResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<qntCygnusWF.Cygnus.WC_CREAR_ROLPERSONASResponse> qntCygnusWF.Cygnus.WSPersonasCygnusSoap.WC_CREAR_ROLPERSONASAsync(qntCygnusWF.Cygnus.WC_CREAR_ROLPERSONASRequest request) {
            return base.Channel.WC_CREAR_ROLPERSONASAsync(request);
        }
        
        public System.Threading.Tasks.Task<qntCygnusWF.Cygnus.WC_CREAR_ROLPERSONASResponse> WC_CREAR_ROLPERSONASAsync(string pws_codigoPer, string pws_numRol, string pws_fechaInicio, string pws_bd, string pws_usu, string pws_psw) {
            qntCygnusWF.Cygnus.WC_CREAR_ROLPERSONASRequest inValue = new qntCygnusWF.Cygnus.WC_CREAR_ROLPERSONASRequest();
            inValue.Body = new qntCygnusWF.Cygnus.WC_CREAR_ROLPERSONASRequestBody();
            inValue.Body.pws_codigoPer = pws_codigoPer;
            inValue.Body.pws_numRol = pws_numRol;
            inValue.Body.pws_fechaInicio = pws_fechaInicio;
            inValue.Body.pws_bd = pws_bd;
            inValue.Body.pws_usu = pws_usu;
            inValue.Body.pws_psw = pws_psw;
            return ((qntCygnusWF.Cygnus.WSPersonasCygnusSoap)(this)).WC_CREAR_ROLPERSONASAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        qntCygnusWF.Cygnus.WC_CREAR_PERSONASResponse qntCygnusWF.Cygnus.WSPersonasCygnusSoap.WC_CREAR_PERSONAS(qntCygnusWF.Cygnus.WC_CREAR_PERSONASRequest request) {
            return base.Channel.WC_CREAR_PERSONAS(request);
        }
        
        public string WC_CREAR_PERSONAS(
                    string p_dfn_nat_codigo, 
                    string p_w_s_tipodepersona, 
                    string p_dfs_nat_codaso, 
                    string pws_identific, 
                    string p_dfn_nat_tipcli, 
                    string p_w_n_tipoiden, 
                    string p_dfn_nat_lugexp, 
                    string p_w_d_fecexp, 
                    string p_dfs_nat_nombres, 
                    string p_dfs_nat_apellidos, 
                    string p_dfn_nat_ciunac, 
                    string p_w_d_fecnac, 
                    string p_cbs_nat_res_aux, 
                    string p_w_d_fecres, 
                    string p_w_s_sexo, 
                    string p_s_tesoro, 
                    string p_dfs_nat_estciv, 
                    string p_dfn_nat_percar, 
                    string p_dfs_nat_cla, 
                    string p_dfs_nat_claint, 
                    string p_dfs_nat_nroact, 
                    string p_df_nat_rut, 
                    string p_df_cod_of, 
                    string p_dfn_nacionalidad, 
                    string p_dfn_nacionalidad2, 
                    string p_dfn_NroHijos, 
                    string p_dfs_nat_apellido1, 
                    string p_dfs_nat_apellido2, 
                    string p_cmb_Estrato, 
                    string p_cb_nat_mujer_fam, 
                    string p_cb_operacion_ext, 
                    string p_estado_act, 
                    string p_w_s_direccion, 
                    string p_w_n_ciudad, 
                    string p_w_s_telefono, 
                    string p_w_s_direcelec, 
                    string ps_i_vinculac_lab, 
                    string ps_c_asesor_com, 
                    string ps_n_salario, 
                    string ps_i_nivel_estudio, 
                    string ps_i_profesion, 
                    string ps_i_cargo, 
                    string ps_i_tipo_cont, 
                    string ps_n_modeloScoring, 
                    string pws_bd, 
                    string pws_usu, 
                    string pws_psw) {
            qntCygnusWF.Cygnus.WC_CREAR_PERSONASRequest inValue = new qntCygnusWF.Cygnus.WC_CREAR_PERSONASRequest();
            inValue.Body = new qntCygnusWF.Cygnus.WC_CREAR_PERSONASRequestBody();
            inValue.Body.p_dfn_nat_codigo = p_dfn_nat_codigo;
            inValue.Body.p_w_s_tipodepersona = p_w_s_tipodepersona;
            inValue.Body.p_dfs_nat_codaso = p_dfs_nat_codaso;
            inValue.Body.pws_identific = pws_identific;
            inValue.Body.p_dfn_nat_tipcli = p_dfn_nat_tipcli;
            inValue.Body.p_w_n_tipoiden = p_w_n_tipoiden;
            inValue.Body.p_dfn_nat_lugexp = p_dfn_nat_lugexp;
            inValue.Body.p_w_d_fecexp = p_w_d_fecexp;
            inValue.Body.p_dfs_nat_nombres = p_dfs_nat_nombres;
            inValue.Body.p_dfs_nat_apellidos = p_dfs_nat_apellidos;
            inValue.Body.p_dfn_nat_ciunac = p_dfn_nat_ciunac;
            inValue.Body.p_w_d_fecnac = p_w_d_fecnac;
            inValue.Body.p_cbs_nat_res_aux = p_cbs_nat_res_aux;
            inValue.Body.p_w_d_fecres = p_w_d_fecres;
            inValue.Body.p_w_s_sexo = p_w_s_sexo;
            inValue.Body.p_s_tesoro = p_s_tesoro;
            inValue.Body.p_dfs_nat_estciv = p_dfs_nat_estciv;
            inValue.Body.p_dfn_nat_percar = p_dfn_nat_percar;
            inValue.Body.p_dfs_nat_cla = p_dfs_nat_cla;
            inValue.Body.p_dfs_nat_claint = p_dfs_nat_claint;
            inValue.Body.p_dfs_nat_nroact = p_dfs_nat_nroact;
            inValue.Body.p_df_nat_rut = p_df_nat_rut;
            inValue.Body.p_df_cod_of = p_df_cod_of;
            inValue.Body.p_dfn_nacionalidad = p_dfn_nacionalidad;
            inValue.Body.p_dfn_nacionalidad2 = p_dfn_nacionalidad2;
            inValue.Body.p_dfn_NroHijos = p_dfn_NroHijos;
            inValue.Body.p_dfs_nat_apellido1 = p_dfs_nat_apellido1;
            inValue.Body.p_dfs_nat_apellido2 = p_dfs_nat_apellido2;
            inValue.Body.p_cmb_Estrato = p_cmb_Estrato;
            inValue.Body.p_cb_nat_mujer_fam = p_cb_nat_mujer_fam;
            inValue.Body.p_cb_operacion_ext = p_cb_operacion_ext;
            inValue.Body.p_estado_act = p_estado_act;
            inValue.Body.p_w_s_direccion = p_w_s_direccion;
            inValue.Body.p_w_n_ciudad = p_w_n_ciudad;
            inValue.Body.p_w_s_telefono = p_w_s_telefono;
            inValue.Body.p_w_s_direcelec = p_w_s_direcelec;
            inValue.Body.ps_i_vinculac_lab = ps_i_vinculac_lab;
            inValue.Body.ps_c_asesor_com = ps_c_asesor_com;
            inValue.Body.ps_n_salario = ps_n_salario;
            inValue.Body.ps_i_nivel_estudio = ps_i_nivel_estudio;
            inValue.Body.ps_i_profesion = ps_i_profesion;
            inValue.Body.ps_i_cargo = ps_i_cargo;
            inValue.Body.ps_i_tipo_cont = ps_i_tipo_cont;
            inValue.Body.ps_n_modeloScoring = ps_n_modeloScoring;
            inValue.Body.pws_bd = pws_bd;
            inValue.Body.pws_usu = pws_usu;
            inValue.Body.pws_psw = pws_psw;
            qntCygnusWF.Cygnus.WC_CREAR_PERSONASResponse retVal = ((qntCygnusWF.Cygnus.WSPersonasCygnusSoap)(this)).WC_CREAR_PERSONAS(inValue);
            return retVal.Body.WC_CREAR_PERSONASResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<qntCygnusWF.Cygnus.WC_CREAR_PERSONASResponse> qntCygnusWF.Cygnus.WSPersonasCygnusSoap.WC_CREAR_PERSONASAsync(qntCygnusWF.Cygnus.WC_CREAR_PERSONASRequest request) {
            return base.Channel.WC_CREAR_PERSONASAsync(request);
        }
        
        public System.Threading.Tasks.Task<qntCygnusWF.Cygnus.WC_CREAR_PERSONASResponse> WC_CREAR_PERSONASAsync(
                    string p_dfn_nat_codigo, 
                    string p_w_s_tipodepersona, 
                    string p_dfs_nat_codaso, 
                    string pws_identific, 
                    string p_dfn_nat_tipcli, 
                    string p_w_n_tipoiden, 
                    string p_dfn_nat_lugexp, 
                    string p_w_d_fecexp, 
                    string p_dfs_nat_nombres, 
                    string p_dfs_nat_apellidos, 
                    string p_dfn_nat_ciunac, 
                    string p_w_d_fecnac, 
                    string p_cbs_nat_res_aux, 
                    string p_w_d_fecres, 
                    string p_w_s_sexo, 
                    string p_s_tesoro, 
                    string p_dfs_nat_estciv, 
                    string p_dfn_nat_percar, 
                    string p_dfs_nat_cla, 
                    string p_dfs_nat_claint, 
                    string p_dfs_nat_nroact, 
                    string p_df_nat_rut, 
                    string p_df_cod_of, 
                    string p_dfn_nacionalidad, 
                    string p_dfn_nacionalidad2, 
                    string p_dfn_NroHijos, 
                    string p_dfs_nat_apellido1, 
                    string p_dfs_nat_apellido2, 
                    string p_cmb_Estrato, 
                    string p_cb_nat_mujer_fam, 
                    string p_cb_operacion_ext, 
                    string p_estado_act, 
                    string p_w_s_direccion, 
                    string p_w_n_ciudad, 
                    string p_w_s_telefono, 
                    string p_w_s_direcelec, 
                    string ps_i_vinculac_lab, 
                    string ps_c_asesor_com, 
                    string ps_n_salario, 
                    string ps_i_nivel_estudio, 
                    string ps_i_profesion, 
                    string ps_i_cargo, 
                    string ps_i_tipo_cont, 
                    string ps_n_modeloScoring, 
                    string pws_bd, 
                    string pws_usu, 
                    string pws_psw) {
            qntCygnusWF.Cygnus.WC_CREAR_PERSONASRequest inValue = new qntCygnusWF.Cygnus.WC_CREAR_PERSONASRequest();
            inValue.Body = new qntCygnusWF.Cygnus.WC_CREAR_PERSONASRequestBody();
            inValue.Body.p_dfn_nat_codigo = p_dfn_nat_codigo;
            inValue.Body.p_w_s_tipodepersona = p_w_s_tipodepersona;
            inValue.Body.p_dfs_nat_codaso = p_dfs_nat_codaso;
            inValue.Body.pws_identific = pws_identific;
            inValue.Body.p_dfn_nat_tipcli = p_dfn_nat_tipcli;
            inValue.Body.p_w_n_tipoiden = p_w_n_tipoiden;
            inValue.Body.p_dfn_nat_lugexp = p_dfn_nat_lugexp;
            inValue.Body.p_w_d_fecexp = p_w_d_fecexp;
            inValue.Body.p_dfs_nat_nombres = p_dfs_nat_nombres;
            inValue.Body.p_dfs_nat_apellidos = p_dfs_nat_apellidos;
            inValue.Body.p_dfn_nat_ciunac = p_dfn_nat_ciunac;
            inValue.Body.p_w_d_fecnac = p_w_d_fecnac;
            inValue.Body.p_cbs_nat_res_aux = p_cbs_nat_res_aux;
            inValue.Body.p_w_d_fecres = p_w_d_fecres;
            inValue.Body.p_w_s_sexo = p_w_s_sexo;
            inValue.Body.p_s_tesoro = p_s_tesoro;
            inValue.Body.p_dfs_nat_estciv = p_dfs_nat_estciv;
            inValue.Body.p_dfn_nat_percar = p_dfn_nat_percar;
            inValue.Body.p_dfs_nat_cla = p_dfs_nat_cla;
            inValue.Body.p_dfs_nat_claint = p_dfs_nat_claint;
            inValue.Body.p_dfs_nat_nroact = p_dfs_nat_nroact;
            inValue.Body.p_df_nat_rut = p_df_nat_rut;
            inValue.Body.p_df_cod_of = p_df_cod_of;
            inValue.Body.p_dfn_nacionalidad = p_dfn_nacionalidad;
            inValue.Body.p_dfn_nacionalidad2 = p_dfn_nacionalidad2;
            inValue.Body.p_dfn_NroHijos = p_dfn_NroHijos;
            inValue.Body.p_dfs_nat_apellido1 = p_dfs_nat_apellido1;
            inValue.Body.p_dfs_nat_apellido2 = p_dfs_nat_apellido2;
            inValue.Body.p_cmb_Estrato = p_cmb_Estrato;
            inValue.Body.p_cb_nat_mujer_fam = p_cb_nat_mujer_fam;
            inValue.Body.p_cb_operacion_ext = p_cb_operacion_ext;
            inValue.Body.p_estado_act = p_estado_act;
            inValue.Body.p_w_s_direccion = p_w_s_direccion;
            inValue.Body.p_w_n_ciudad = p_w_n_ciudad;
            inValue.Body.p_w_s_telefono = p_w_s_telefono;
            inValue.Body.p_w_s_direcelec = p_w_s_direcelec;
            inValue.Body.ps_i_vinculac_lab = ps_i_vinculac_lab;
            inValue.Body.ps_c_asesor_com = ps_c_asesor_com;
            inValue.Body.ps_n_salario = ps_n_salario;
            inValue.Body.ps_i_nivel_estudio = ps_i_nivel_estudio;
            inValue.Body.ps_i_profesion = ps_i_profesion;
            inValue.Body.ps_i_cargo = ps_i_cargo;
            inValue.Body.ps_i_tipo_cont = ps_i_tipo_cont;
            inValue.Body.ps_n_modeloScoring = ps_n_modeloScoring;
            inValue.Body.pws_bd = pws_bd;
            inValue.Body.pws_usu = pws_usu;
            inValue.Body.pws_psw = pws_psw;
            return ((qntCygnusWF.Cygnus.WSPersonasCygnusSoap)(this)).WC_CREAR_PERSONASAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        qntCygnusWF.Cygnus.WC_ALMACENAR_ACT_SOLICITANTEResponse qntCygnusWF.Cygnus.WSPersonasCygnusSoap.WC_ALMACENAR_ACT_SOLICITANTE(qntCygnusWF.Cygnus.WC_ALMACENAR_ACT_SOLICITANTERequest request) {
            return base.Channel.WC_ALMACENAR_ACT_SOLICITANTE(request);
        }
        
        public qntCygnusWF.Cygnus.Resultado WC_ALMACENAR_ACT_SOLICITANTE(
                    string ps_identificacion, 
                    string s_actividad, 
                    string s_empresa, 
                    string s_fec_ingreso, 
                    string s_contrato, 
                    string s_cargo, 
                    string s_dir_empresa, 
                    string s_ciudad_empresa, 
                    string s_ingreso_principal, 
                    string s_gastos_obligaciones, 
                    string s_otros_ingresos, 
                    string s_total_activos, 
                    string s_total_ingresomes, 
                    string s_total_pasivo, 
                    string s_renta, 
                    string s_declarante_renta, 
                    string s_vivienda, 
                    string s_prendas_vivienda, 
                    string s_vehiculo, 
                    string s_prendas_vehiculo, 
                    string s_otros_bienes, 
                    string s_otros_descripcion, 
                    string s_barrio, 
                    string ps_db, 
                    string ps_usuario, 
                    string ps_clave) {
            qntCygnusWF.Cygnus.WC_ALMACENAR_ACT_SOLICITANTERequest inValue = new qntCygnusWF.Cygnus.WC_ALMACENAR_ACT_SOLICITANTERequest();
            inValue.Body = new qntCygnusWF.Cygnus.WC_ALMACENAR_ACT_SOLICITANTERequestBody();
            inValue.Body.ps_identificacion = ps_identificacion;
            inValue.Body.s_actividad = s_actividad;
            inValue.Body.s_empresa = s_empresa;
            inValue.Body.s_fec_ingreso = s_fec_ingreso;
            inValue.Body.s_contrato = s_contrato;
            inValue.Body.s_cargo = s_cargo;
            inValue.Body.s_dir_empresa = s_dir_empresa;
            inValue.Body.s_ciudad_empresa = s_ciudad_empresa;
            inValue.Body.s_ingreso_principal = s_ingreso_principal;
            inValue.Body.s_gastos_obligaciones = s_gastos_obligaciones;
            inValue.Body.s_otros_ingresos = s_otros_ingresos;
            inValue.Body.s_total_activos = s_total_activos;
            inValue.Body.s_total_ingresomes = s_total_ingresomes;
            inValue.Body.s_total_pasivo = s_total_pasivo;
            inValue.Body.s_renta = s_renta;
            inValue.Body.s_declarante_renta = s_declarante_renta;
            inValue.Body.s_vivienda = s_vivienda;
            inValue.Body.s_prendas_vivienda = s_prendas_vivienda;
            inValue.Body.s_vehiculo = s_vehiculo;
            inValue.Body.s_prendas_vehiculo = s_prendas_vehiculo;
            inValue.Body.s_otros_bienes = s_otros_bienes;
            inValue.Body.s_otros_descripcion = s_otros_descripcion;
            inValue.Body.s_barrio = s_barrio;
            inValue.Body.ps_db = ps_db;
            inValue.Body.ps_usuario = ps_usuario;
            inValue.Body.ps_clave = ps_clave;
            qntCygnusWF.Cygnus.WC_ALMACENAR_ACT_SOLICITANTEResponse retVal = ((qntCygnusWF.Cygnus.WSPersonasCygnusSoap)(this)).WC_ALMACENAR_ACT_SOLICITANTE(inValue);
            return retVal.Body.WC_ALMACENAR_ACT_SOLICITANTEResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<qntCygnusWF.Cygnus.WC_ALMACENAR_ACT_SOLICITANTEResponse> qntCygnusWF.Cygnus.WSPersonasCygnusSoap.WC_ALMACENAR_ACT_SOLICITANTEAsync(qntCygnusWF.Cygnus.WC_ALMACENAR_ACT_SOLICITANTERequest request) {
            return base.Channel.WC_ALMACENAR_ACT_SOLICITANTEAsync(request);
        }
        
        public System.Threading.Tasks.Task<qntCygnusWF.Cygnus.WC_ALMACENAR_ACT_SOLICITANTEResponse> WC_ALMACENAR_ACT_SOLICITANTEAsync(
                    string ps_identificacion, 
                    string s_actividad, 
                    string s_empresa, 
                    string s_fec_ingreso, 
                    string s_contrato, 
                    string s_cargo, 
                    string s_dir_empresa, 
                    string s_ciudad_empresa, 
                    string s_ingreso_principal, 
                    string s_gastos_obligaciones, 
                    string s_otros_ingresos, 
                    string s_total_activos, 
                    string s_total_ingresomes, 
                    string s_total_pasivo, 
                    string s_renta, 
                    string s_declarante_renta, 
                    string s_vivienda, 
                    string s_prendas_vivienda, 
                    string s_vehiculo, 
                    string s_prendas_vehiculo, 
                    string s_otros_bienes, 
                    string s_otros_descripcion, 
                    string s_barrio, 
                    string ps_db, 
                    string ps_usuario, 
                    string ps_clave) {
            qntCygnusWF.Cygnus.WC_ALMACENAR_ACT_SOLICITANTERequest inValue = new qntCygnusWF.Cygnus.WC_ALMACENAR_ACT_SOLICITANTERequest();
            inValue.Body = new qntCygnusWF.Cygnus.WC_ALMACENAR_ACT_SOLICITANTERequestBody();
            inValue.Body.ps_identificacion = ps_identificacion;
            inValue.Body.s_actividad = s_actividad;
            inValue.Body.s_empresa = s_empresa;
            inValue.Body.s_fec_ingreso = s_fec_ingreso;
            inValue.Body.s_contrato = s_contrato;
            inValue.Body.s_cargo = s_cargo;
            inValue.Body.s_dir_empresa = s_dir_empresa;
            inValue.Body.s_ciudad_empresa = s_ciudad_empresa;
            inValue.Body.s_ingreso_principal = s_ingreso_principal;
            inValue.Body.s_gastos_obligaciones = s_gastos_obligaciones;
            inValue.Body.s_otros_ingresos = s_otros_ingresos;
            inValue.Body.s_total_activos = s_total_activos;
            inValue.Body.s_total_ingresomes = s_total_ingresomes;
            inValue.Body.s_total_pasivo = s_total_pasivo;
            inValue.Body.s_renta = s_renta;
            inValue.Body.s_declarante_renta = s_declarante_renta;
            inValue.Body.s_vivienda = s_vivienda;
            inValue.Body.s_prendas_vivienda = s_prendas_vivienda;
            inValue.Body.s_vehiculo = s_vehiculo;
            inValue.Body.s_prendas_vehiculo = s_prendas_vehiculo;
            inValue.Body.s_otros_bienes = s_otros_bienes;
            inValue.Body.s_otros_descripcion = s_otros_descripcion;
            inValue.Body.s_barrio = s_barrio;
            inValue.Body.ps_db = ps_db;
            inValue.Body.ps_usuario = ps_usuario;
            inValue.Body.ps_clave = ps_clave;
            return ((qntCygnusWF.Cygnus.WSPersonasCygnusSoap)(this)).WC_ALMACENAR_ACT_SOLICITANTEAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        qntCygnusWF.Cygnus.pruebaConexionResponse qntCygnusWF.Cygnus.WSPersonasCygnusSoap.pruebaConexion(qntCygnusWF.Cygnus.pruebaConexionRequest request) {
            return base.Channel.pruebaConexion(request);
        }
        
        public qntCygnusWF.Cygnus.RespuestaPermite pruebaConexion(string pws_bd, string pws_usu, string pws_psw) {
            qntCygnusWF.Cygnus.pruebaConexionRequest inValue = new qntCygnusWF.Cygnus.pruebaConexionRequest();
            inValue.Body = new qntCygnusWF.Cygnus.pruebaConexionRequestBody();
            inValue.Body.pws_bd = pws_bd;
            inValue.Body.pws_usu = pws_usu;
            inValue.Body.pws_psw = pws_psw;
            qntCygnusWF.Cygnus.pruebaConexionResponse retVal = ((qntCygnusWF.Cygnus.WSPersonasCygnusSoap)(this)).pruebaConexion(inValue);
            return retVal.Body.pruebaConexionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<qntCygnusWF.Cygnus.pruebaConexionResponse> qntCygnusWF.Cygnus.WSPersonasCygnusSoap.pruebaConexionAsync(qntCygnusWF.Cygnus.pruebaConexionRequest request) {
            return base.Channel.pruebaConexionAsync(request);
        }
        
        public System.Threading.Tasks.Task<qntCygnusWF.Cygnus.pruebaConexionResponse> pruebaConexionAsync(string pws_bd, string pws_usu, string pws_psw) {
            qntCygnusWF.Cygnus.pruebaConexionRequest inValue = new qntCygnusWF.Cygnus.pruebaConexionRequest();
            inValue.Body = new qntCygnusWF.Cygnus.pruebaConexionRequestBody();
            inValue.Body.pws_bd = pws_bd;
            inValue.Body.pws_usu = pws_usu;
            inValue.Body.pws_psw = pws_psw;
            return ((qntCygnusWF.Cygnus.WSPersonasCygnusSoap)(this)).pruebaConexionAsync(inValue);
        }
    }
}
